Update dotnet.yml

diff --git a/.github/workflows/dotnet.yml b/.github/workflows/dotnet.yml
--- a/.github/workflows/dotnet.yml
+++ b/.github/workflows/dotnet.yml
@@ -25,8 +25,8 @@ jobs:
     - name: Test with TRX file
       run: dotnet test --logger "trx;LogFileName=TestResults.trx"
     
-    - name: Test with Xunit XML file
-      run: dotnet test --logger "xunit;LogFileName=TestResults.xml" 
+   # - name: Test with Xunit XML file
+     #  run: dotnet test --logger "xunit;LogFileName=TestResults.xml" 
       
     - name: Archive test results
       uses: actions/upload-artifact@v2
@@ -35,11 +35,11 @@ jobs:
         name: Artifact for TRX files
         path: test/**/TestResults.trx
         
-    - name: Archive test results
-      uses: actions/upload-artifact@v2
-      if: success() || failure()
-      with:
-        name: Artifact for Xunit XML files
-        path: test/**/TestResults.xml
+    #- name: Archive test results
+     # uses: actions/upload-artifact@v2
+      #if: success() || failure()
+      #with:
+       # name: Artifact for Xunit XML files
+        #path: test/**/TestResults.xml
         
       
